export const ON_SET_SOUND = 'ON_SET_SOUND';
export const SET_ROUND_COUNT = 'SET_ROUND_COUNT';
export const SET_BIG_BREAK_NUMBER = 'SET_BIG_BREAK_NUMBER';
export const SET_WORK_TIME = 'SET_WORK_TIME';
export const SET_BREAK_TIME = 'SET_BREAK_TIME';
export const SET_LONG_BREAK_TIME = 'SET_LONG_BREAK_TIME';
export const SET_DEFAULT_SETTINGS = 'SET_DEFAULT_SETTINGS';
