export const ON_SET_SHOW_SETTINGS = 'ON_SET_SHOW_SETTINGS';
export const ON_SET_IS_PLAY = 'ON_SET_IS_PLAY';
export const ON_CHANGE_TYPE_TIME = 'ON_CHANGE_TYPE_TIME';
export const ON_SET_CURRENT_ROUND = 'ON_SET_CURRENT_ROUND';
